/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v1/api/auth/register": {
    /**
     * Register
     * @description Register a new user.
     */
    post: operations["register_v1_api_auth_register_post"];
  };
  "/v1/api/auth/login": {
    /**
     * Login
     * @description Login user.
     */
    post: operations["login_v1_api_auth_login_post"];
  };
  "/v1/api/auth/logout": {
    /**
     * Logout
     * @description Logout user.
     */
    post: operations["logout_v1_api_auth_logout_post"];
  };
  "/v1/api/auth/refresh": {
    /**
     * Refresh Token
     * @description Refresh access token using refresh token.
     */
    post: operations["refresh_token_v1_api_auth_refresh_post"];
  };
  "/v1/api/users/me": {
    /**
     * Get User Profile
     * @description Get current user's profile.
     */
    get: operations["get_user_profile_v1_api_users_me_get"];
    /**
     * Update User Profile
     * @description Update current user's profile.
     */
    put: operations["update_user_profile_v1_api_users_me_put"];
  };
  "/v1/api/user/detailed-cvs": {
    /**
     * Get User Detailed Cvs
     * @description Get all user's detailed CVs.
     */
    get: operations["get_user_detailed_cvs_v1_api_user_detailed_cvs_get"];
  };
  "/v1/api/user/detailed-cvs/{language_code}": {
    /**
     * Get User Detailed Cv
     * @description Get user's detailed CV by language.
     */
    get: operations["get_user_detailed_cv_v1_api_user_detailed_cvs__language_code__get"];
    /**
     * Upsert User Detailed Cv
     * @description Create or update user's detailed CV for a language.
     */
    put: operations["upsert_user_detailed_cv_v1_api_user_detailed_cvs__language_code__put"];
    /**
     * Delete User Detailed Cv
     * @description Delete user's detailed CV by language.
     */
    delete: operations["delete_user_detailed_cv_v1_api_user_detailed_cvs__language_code__delete"];
  };
  "/v1/api/user/detailed-cvs/{language_code}/primary": {
    /**
     * Set Primary Cv
     * @description Set a CV as primary.
     */
    put: operations["set_primary_cv_v1_api_user_detailed_cvs__language_code__primary_put"];
  };
  "/v1/api/jobs": {
    /**
     * Get Jobs
     * @description Get all job descriptions for a language.
     */
    get: operations["get_jobs_v1_api_jobs_get"];
    /**
     * Create Job
     * @description Create new job description.
     */
    post: operations["create_job_v1_api_jobs_post"];
  };
  "/v1/api/jobs/{job_id}": {
    /**
     * Get Job
     * @description Get job description by ID.
     */
    get: operations["get_job_v1_api_jobs__job_id__get"];
    /**
     * Update Job
     * @description Update job description.
     */
    put: operations["update_job_v1_api_jobs__job_id__put"];
    /**
     * Delete Job
     * @description Delete job description.
     */
    delete: operations["delete_job_v1_api_jobs__job_id__delete"];
  };
  "/v1/api/generations/competences": {
    /**
     * Generate Competences
     * @description Generate core competences from CV and job description.
     */
    post: operations["generate_competences_v1_api_generations_competences_post"];
  };
  "/v1/api/generations/cv": {
    /**
     * Generate Cv
     * @description Generate a complete CV using core competences.
     */
    post: operations["generate_cv_v1_api_generations_cv_post"];
  };
  "/v1/api/generations": {
    /**
     * Get User Generations
     * @description Get all generated CVs for current user.
     */
    get: operations["get_user_generations_v1_api_generations_get"];
    /**
     * Generate And Save Cv
     * @description Generate and save a new CV for job application.
     */
    post: operations["generate_and_save_cv_v1_api_generations_post"];
  };
  "/v1/api/generations/{cv_id}": {
    /**
     * Get Generated Cv
     * @description Get a specific generated CV.
     */
    get: operations["get_generated_cv_v1_api_generations__cv_id__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * AuthResponse
     * @description Schema for authentication response.
     */
    AuthResponse: {
      /** Access Token */
      access_token: string;
      /** Refresh Token */
      refresh_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type?: string;
      user: components["schemas"]["UserResponse"];
    };
    /** Body_login_v1_api_auth_login_post */
    Body_login_v1_api_auth_login_post: {
      /** Grant Type */
      grant_type?: string | null;
      /** Username */
      username: string;
      /** Password */
      password: string;
      /**
       * Scope
       * @default
       */
      scope?: string;
      /** Client Id */
      client_id?: string | null;
      /** Client Secret */
      client_secret?: string | null;
    };
    /** Body_refresh_token_v1_api_auth_refresh_post */
    Body_refresh_token_v1_api_auth_refresh_post: {
      /** Token */
      token: string;
    };
    /** ContactRequest */
    ContactRequest: {
      /** Value */
      value: string;
      /** Type */
      type: string;
      /** Icon */
      icon?: string | null;
      /** Url */
      url?: string | null;
    };
    /**
     * DetailedCVCreate
     * @description Schema for creating a detailed CV.
     */
    DetailedCVCreate: {
      /** Language Code */
      language_code: string;
      /** Content */
      content: Record<string, never>;
      /**
       * Is Primary
       * @default false
       */
      is_primary?: boolean;
    };
    /**
     * DetailedCVResponse
     * @description Schema for detailed CV responses.
     */
    DetailedCVResponse: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Updated At */
      updated_at?: string | null;
      /** Language Code */
      language_code: string;
      /** Content */
      content: Record<string, never>;
      /**
       * Is Primary
       * @default false
       */
      is_primary?: boolean;
      /** Id */
      id: number;
      /** User Id */
      user_id: number;
    };
    /** GenerateCVRequest */
    GenerateCVRequest: {
      /** Cv Text */
      cv_text: string;
      /** Job Description */
      job_description: string;
      personal_info: components["schemas"]["PersonalInfo"];
      /** Approved Competences */
      approved_competences: string[];
      /** Notes */
      notes?: string | null;
    };
    /** GenerateCompetencesRequest */
    GenerateCompetencesRequest: {
      /** Cv Text */
      cv_text: string;
      /** Job Description */
      job_description: string;
      /** Notes */
      notes?: string | null;
    };
    /**
     * GeneratedCVCreate
     * @description Schema for creating a generated CV.
     */
    GeneratedCVCreate: {
      /** Language Code */
      language_code: string;
      /** Content */
      content: Record<string, never>;
      /** Detailed Cv Id */
      detailed_cv_id: number;
      /** Job Description Id */
      job_description_id: number;
    };
    /**
     * GeneratedCVResponse
     * @description Schema for generated CV responses.
     */
    GeneratedCVResponse: {
      /** Language Code */
      language_code: string;
      /** Content */
      content: Record<string, never>;
      /** Id */
      id: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** User Id */
      user_id: number;
      /** Detailed Cv Id */
      detailed_cv_id: number;
      /** Job Description Id */
      job_description_id: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * JobDescriptionCreate
     * @description Schema for creating a job description.
     */
    JobDescriptionCreate: {
      /** Title */
      title: string;
      /** Description */
      description: string;
      /** Language Code */
      language_code: string;
    };
    /**
     * JobDescriptionResponse
     * @description Schema for job description responses.
     */
    JobDescriptionResponse: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Updated At */
      updated_at?: string | null;
      /** Title */
      title: string;
      /** Description */
      description: string;
      /** Language Code */
      language_code: string;
      /** Id */
      id: number;
    };
    /**
     * JobDescriptionUpdate
     * @description Schema for updating a job description.
     */
    JobDescriptionUpdate: {
      /** Title */
      title?: string | null;
      /** Description */
      description?: string | null;
    };
    /** PersonalInfo */
    PersonalInfo: {
      /** Full Name */
      full_name: string;
      email: components["schemas"]["ContactRequest"];
      phone?: components["schemas"]["ContactRequest"] | null;
      location?: components["schemas"]["ContactRequest"] | null;
    };
    /**
     * UserCreate
     * @description Schema for creating a new user.
     */
    UserCreate: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /**
     * UserResponse
     * @description Schema for user responses.
     */
    UserResponse: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Id */
      id: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Personal Info */
      personal_info?: Record<string, never> | null;
    };
    /**
     * UserUpdate
     * @description Schema for updating a user's personal info.
     */
    UserUpdate: {
      /** Personal Info */
      personal_info: Record<string, never>;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Register
   * @description Register a new user.
   */
  register_v1_api_auth_register_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      /** @description Bad Request - Email already registered */
      400: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Login
   * @description Login user.
   */
  login_v1_api_auth_login_post: {
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_login_v1_api_auth_login_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Logout
   * @description Logout user.
   */
  logout_v1_api_auth_logout_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  /**
   * Refresh Token
   * @description Refresh access token using refresh token.
   */
  refresh_token_v1_api_auth_refresh_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Body_refresh_token_v1_api_auth_refresh_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get User Profile
   * @description Get current user's profile.
   */
  get_user_profile_v1_api_users_me_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  /**
   * Update User Profile
   * @description Update current user's profile.
   */
  update_user_profile_v1_api_users_me_put: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get User Detailed Cvs
   * @description Get all user's detailed CVs.
   */
  get_user_detailed_cvs_v1_api_user_detailed_cvs_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DetailedCVResponse"][];
        };
      };
    };
  };
  /**
   * Get User Detailed Cv
   * @description Get user's detailed CV by language.
   */
  get_user_detailed_cv_v1_api_user_detailed_cvs__language_code__get: {
    parameters: {
      path: {
        language_code: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DetailedCVResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Upsert User Detailed Cv
   * @description Create or update user's detailed CV for a language.
   */
  upsert_user_detailed_cv_v1_api_user_detailed_cvs__language_code__put: {
    parameters: {
      path: {
        language_code: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DetailedCVCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DetailedCVResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Delete User Detailed Cv
   * @description Delete user's detailed CV by language.
   */
  delete_user_detailed_cv_v1_api_user_detailed_cvs__language_code__delete: {
    parameters: {
      path: {
        language_code: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Set Primary Cv
   * @description Set a CV as primary.
   */
  set_primary_cv_v1_api_user_detailed_cvs__language_code__primary_put: {
    parameters: {
      path: {
        language_code: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DetailedCVResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Jobs
   * @description Get all job descriptions for a language.
   */
  get_jobs_v1_api_jobs_get: {
    parameters: {
      query?: {
        language_code?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["JobDescriptionResponse"][];
        };
      };
      /** @description Unauthorized - Invalid or missing token */
      401: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Create Job
   * @description Create new job description.
   */
  create_job_v1_api_jobs_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["JobDescriptionCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["JobDescriptionResponse"];
        };
      };
      /** @description Unauthorized - Invalid or missing token */
      401: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Job
   * @description Get job description by ID.
   */
  get_job_v1_api_jobs__job_id__get: {
    parameters: {
      path: {
        job_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["JobDescriptionResponse"];
        };
      };
      /** @description Unauthorized - Invalid or missing token */
      401: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Job not found */
      404: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update Job
   * @description Update job description.
   */
  update_job_v1_api_jobs__job_id__put: {
    parameters: {
      path: {
        job_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JobDescriptionUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["JobDescriptionResponse"];
        };
      };
      /** @description Unauthorized - Invalid or missing token */
      401: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Job not found */
      404: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Delete Job
   * @description Delete job description.
   */
  delete_job_v1_api_jobs__job_id__delete: {
    parameters: {
      path: {
        job_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Unauthorized - Invalid or missing token */
      401: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Job not found */
      404: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Generate Competences
   * @description Generate core competences from CV and job description.
   */
  generate_competences_v1_api_generations_competences_post: {
    parameters: {
      query?: {
        language_code?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenerateCompetencesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: string[];
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Generate Cv
   * @description Generate a complete CV using core competences.
   */
  generate_cv_v1_api_generations_cv_post: {
    parameters: {
      query?: {
        language_code?: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenerateCVRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get User Generations
   * @description Get all generated CVs for current user.
   */
  get_user_generations_v1_api_generations_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GeneratedCVResponse"][];
        };
      };
    };
  };
  /**
   * Generate And Save Cv
   * @description Generate and save a new CV for job application.
   */
  generate_and_save_cv_v1_api_generations_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GeneratedCVCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GeneratedCVResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Generated Cv
   * @description Get a specific generated CV.
   */
  get_generated_cv_v1_api_generations__cv_id__get: {
    parameters: {
      path: {
        cv_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GeneratedCVResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
