/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FullName = string;
export type Value = string;
/**
 * e.g., 'Email', 'Phone', 'Location'
 */
export type Type = string;
/**
 * e.g., 'email', 'phone', 'linkedin'
 */
export type Icon = string | null;
/**
 * Optional URL for the contact (e.g., mailto:, tel:, https://)
 */
export type Url = string | null;
export type Text = string;
export type Text1 = string;
export type Text2 = string;
export type CoreCompetences = CoreCompetenceDTO[];
export type Name = string;
export type Description = string | null;
export type Location = string | null;
export type Position = string;
export type StartDate = string;
export type EndDate = string | null;
export type Description1 = string;
export type Technologies = string[];
export type Experiences = ExperienceDTO[];
export type Degree = string;
export type StartDate1 = string;
export type EndDate1 = string | null;
export type Description2 = string;
export type Education = EducationDTO[];
export type Name1 = string;
export type Text3 = string;
export type Skills1 = SkillDTO[];
export type Skills = SkillGroupDTO[];
/**
 * Standardized language codes.
 */
export type LanguageCode = "en" | "fr" | "de" | "es" | "it";
export type Value1 = string;
export type Type1 = string;
export type Icon1 = string | null;
export type Url1 = string | null;
export type CvText = string;
export type JobDescription = string;
export type FullName1 = string;
export type ApprovedCompetences = string[];
export type Notes = string | null;
export type CvText1 = string;
export type JobDescription1 = string;
export type Notes1 = string | null;
export type CoreCompetences1 = CoreCompetenceDTO[];
export type Experiences1 = ExperienceDTO[];
export type Education1 = EducationDTO[];
export type Skills2 = SkillGroupDTO[];

export interface Stdin {
  CVDTO: CVDTO;
  ContactDTO: ContactDTO;
  ContactRequest: ContactRequest;
  CoreCompetenceDTO: CoreCompetenceDTO;
  EducationDTO: EducationDTO;
  ExperienceDTO: ExperienceDTO;
  GenerateCVRequest: GenerateCVRequest;
  GenerateCompetencesRequest: GenerateCompetencesRequest;
  InstitutionDTO: InstitutionDTO;
  Language: Language;
  LanguageCode: LanguageCode;
  MinimalCVDTO: MinimalCVDTO;
  PersonalInfo: PersonalInfo;
  PersonalInfoDTO: PersonalInfoDTO;
  SkillDTO: SkillDTO;
  SkillGroupDTO: SkillGroupDTO;
  SummaryDTO: SummaryDTO;
  TitleDTO: TitleDTO;
  [k: string]: unknown;
}
export interface CVDTO {
  personal_info: PersonalInfoDTO;
  title: TitleDTO;
  summary: SummaryDTO;
  core_competences: CoreCompetences;
  experiences: Experiences;
  education: Education;
  skills: Skills;
  language: Language;
  [k: string]: unknown;
}
/**
 * Personal information with flexible contact handling.
 */
export interface PersonalInfoDTO {
  full_name: FullName;
  email?: ContactDTO | null;
  phone?: ContactDTO | null;
  location?: ContactDTO | null;
  linkedin?: ContactDTO | null;
  github?: ContactDTO | null;
  [k: string]: unknown;
}
/**
 * Represents a single contact method with optional metadata.
 */
export interface ContactDTO {
  value: Value;
  type: Type;
  icon?: Icon;
  url?: Url;
  [k: string]: unknown;
}
export interface TitleDTO {
  text: Text;
  [k: string]: unknown;
}
export interface SummaryDTO {
  text: Text1;
  [k: string]: unknown;
}
export interface CoreCompetenceDTO {
  text: Text2;
  [k: string]: unknown;
}
export interface ExperienceDTO {
  company: InstitutionDTO;
  position: Position;
  start_date: StartDate;
  end_date?: EndDate;
  description?: Description1;
  technologies?: Technologies;
  [k: string]: unknown;
}
export interface InstitutionDTO {
  name: Name;
  description?: Description;
  location?: Location;
  [k: string]: unknown;
}
export interface EducationDTO {
  university: InstitutionDTO;
  degree: Degree;
  start_date: StartDate1;
  end_date?: EndDate1;
  description?: Description2;
  [k: string]: unknown;
}
export interface SkillGroupDTO {
  name: Name1;
  skills: Skills1;
  [k: string]: unknown;
}
export interface SkillDTO {
  text: Text3;
  [k: string]: unknown;
}
/**
 * Core language identity.
 */
export interface Language {
  code: LanguageCode;
  [k: string]: unknown;
}
export interface ContactRequest {
  value: Value1;
  type: Type1;
  icon?: Icon1;
  url?: Url1;
  [k: string]: unknown;
}
export interface GenerateCVRequest {
  cv_text: CvText;
  job_description: JobDescription;
  personal_info: PersonalInfo;
  approved_competences: ApprovedCompetences;
  notes?: Notes;
  [k: string]: unknown;
}
export interface PersonalInfo {
  full_name: FullName1;
  email: ContactRequest;
  phone?: ContactRequest | null;
  location?: ContactRequest | null;
  [k: string]: unknown;
}
export interface GenerateCompetencesRequest {
  cv_text: CvText1;
  job_description: JobDescription1;
  notes?: Notes1;
  [k: string]: unknown;
}
export interface MinimalCVDTO {
  title: TitleDTO;
  core_competences: CoreCompetences1;
  experiences: Experiences1;
  education: Education1;
  skills: Skills2;
  language: Language;
  [k: string]: unknown;
}

export interface GenerateCompetencesResponse {
    competences: string[];
}
