---
name: CI pipeline

on:
  pull_request:
  push:
    branches: ['main']
    tags: ['v*.*.*']
  workflow_dispatch:

jobs:
  pre_commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - run: uv sync --frozen --group dev
      - run: uv run pre-commit run --all-files

  lint:
    name: Linting checks
    runs-on: ubuntu-latest
    needs: pre_commit
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - run: uv sync --frozen --group dev
      - name: Run linting checks
        run: |
          uv run ruff check .
          uv run mypy .

  pytest:
    name: Run Pytest
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - run: uv sync --frozen --group dev
      - name: Run tests
        run: |
          uv run pytest tests

  docs:
    name: Build and deploy documentation
    needs: pytest
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
    concurrency:
      group: "pages"
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - run: uv sync --frozen --group dev
      - run: uv pip install -e .
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Build documentation
        run: uv run mkdocs build --strict
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
