---
name: CI pipeline

on:
  pull_request:
  push:
    branches: ['**']
    tags: ['v*.*.*']
  workflow_dispatch:

jobs:
  pre_commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      # Synchronize dependencies and extras
      - run: uv sync --all-extras
      - run: uv run pre-commit run --all-files

  pytest:
    name: Run Pytest
    runs-on: ubuntu-latest
    needs: pre_commit
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - run: uv sync --all-extras
      - name: Run tests
        run: |
          uv run pytest tests
